### PR TITLE
Update plugin.xml

### PR DESCRIPTION
**Pull request by brandonday**

### CODE REVIEW

**Comment by brandonday** [comment]
k

**Comment by Hirbod** [comment]
You should Not Share your private API key with us :))

**Comment by brandonday** [comment]
Is it still there? I'm a complete github noob. I shared by accident.

**Comment by brandonday** [comment]
Btw, I'm having issues with this plugin not having 64bit architecture.

**Comment by Hirbod** [comment]
Please login to your Google console and change your key. It is still here and will last forever

**Comment by brandonday** [comment]
Alright, thank you very much for making me aware of this. I have logged in and changed my key. Thanks again.

**Pull request closed without merging**
