### PR TITLE
Cordova 5.0

### PR DESCRIPTION
**Pull request by Nipher**
Ref #516

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Cool! Quick question though - why are you suppressing the deprecation warnings?

**Comment by enebe-nb** [comment]
there's also a signature change on method `org.apache.cordova.CordovaPlugin$privateInitialize` that need to be handled:
```
diff --git a/src/android/plugin/google/maps/GoogleMaps.java b/src/android/plugin/google/maps/GoogleMaps.java
index 3b187ff..78679b1 100644
--- a/src/android/plugin/google/maps/GoogleMaps.java
+++ b/src/android/plugin/google/maps/GoogleMaps.java
@@ -622,9 +621,9 @@ public class GoogleMaps extends CordovaPlugin implements View.OnClickListener, O
       try {
         Class cordovaPref = Class.forName("org.apache.cordova.CordovaPreferences");
         if (cordovaPref != null) {
-          Method privateInit = CordovaPlugin.class.getMethod("privateInitialize", CordovaInterface.class, CordovaWebView.class, cordovaPref);
+          Method privateInit = CordovaPlugin.class.getMethod("privateInitialize", String.class, CordovaInterface.class, CordovaWebView.class, cordovaPref);
           if (privateInit != null) {
-            privateInit.invoke(plugin, this.cordova, webView, null);
+            privateInit.invoke(plugin, "plugin.google.maps.Plugin" + serviceName, this.cordova, webView, null);
           }
         }
       } catch (Exception e2) {}
```

and the `getView()` got escaped here (however i don't know why its use invoke):
```
@@ -203,10 +202,10 @@ public class GoogleMaps extends CordovaPlugin implements View.OnClickListener, O
         }
         if (VERSION.SDK_INT <= Build.VERSION_CODES.ICE_CREAM_SANDWICH_MR1) {
           Log.d(TAG, "Google Maps Plugin reloads the browser to change the background color as transparent.");
           webView.getView().setBackgroundColor(0);
             try {
-              Method method = webView.getClass().getMethod("reload");
-              method.invoke(webView);
+              Method method = webView.getView().getClass().getMethod("reload");
+              method.invoke(webView.getView());
             } catch (Exception e) {
               e.printStackTrace();
             }
```

**Comment by alexislg2** [comment]
My app is crashing at startup after I installed this new plugin version. Anyone else experiences this?(Android 5 + cordova 5.1.1)

**Comment by alexislg2** [comment]
Hey it not working for me (cordova 5.0.0):

````
/Users/alexis/mafia/cordova/platforms/android/src/plugin/google/maps/GoogleMaps.java:138: error: cannot find symbol
    root = (ViewGroup) webView.getParent();
                              ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
/Users/alexis/mafia/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:53: error: cannot find symbol
    this.root = (ViewGroup) webView.getParent();
                                   ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
/Users/alexis/mafia/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:261: error: cannot find symbol
        webView.requestFocus(View.FOCUS_DOWN);
               ^
  symbol:   method requestFocus(int)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/alexis/mafia/cordova/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
:compileDebugJava FAILED

FAILURE: Build failed with an exception.
```

**Comment by Hirbod** [comment]
@Nipher 

I tried to check your version for merge, but it fails.

```
/Users/Hirbod/Desktop/appdev/Nachbarschaft/platforms/android/src/plugin/google/maps/GoogleMaps.java:549: error: cannot find symbol
    mapView.getMapAsync(new OnMapReadyCallback() {
           ^
  symbol:   method getMapAsync(<anonymous OnMapReadyCallback>)
  location: variable mapView of type MapView
/Users/Hirbod/Desktop/appdev/Nachbarschaft/platforms/android/src/plugin/google/maps/GoogleMaps.java:999: error: cannot find symbol
        LocationServices.SettingsApi.checkLocationSettings(googleApiClient, builder.build());
                        ^
  symbol:   variable SettingsApi
  location: class LocationServices
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileX86DebugJava FAILED
```

**Comment by Nipher** [comment]
@Hirbod, sorry!
I will try to look into it!
I've got busy with other matters, I would love to fix this, seems like this fork is working just with some people...
Sorry for answering just now...

**Comment by alexislg2** [comment]
I "solved" it:

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/563

Le lun. 20 juil. 2015 20:21, Jonas Mendes <notifications@github.com> a
écrit :

**Comment by Hirbod** [comment]
v.1.2.8 is out and works for Cordova 5+ and Android-Cordova 4.x+
It fixes many other problems and has some new features. The forks outside are tested and unstable and should not be used

**Pull request closed without merging**
