### PR TITLE
Uplift to cordova-android 4.x (Cordova 5.x)

### PR DESCRIPTION
**Pull request by wolf-s**
#516 Tested on cordova 5.2.0/cordova-android 4.1.1 and cordova-android 4.0.2

### CODE REVIEW

**Comment by Hirbod** [comment]
Awesome. Finally a clean cordova-android 4.x / cordova 5.x fix. Who tested this and can confirm that it works?

**Comment by Hirbod** [comment]
Can you also confirm, that your fixes will work with Crosswalk?

**Comment by Hirbod** [comment]
Confirmed, works perfect! You, @wolf-s are my hero and will make a lot of people happy. Release 1.2.8 is out!

**Comment by wolf-s** [comment]
you are very welcome

**Pull request merged**
