### PR TITLE
Implement maxWidth for Marker InfoWindow

### PR DESCRIPTION
**Pull request by trancee**
If there is much text in the content of the InfoWindow, currently it takes up full width of the available map screen and just does not look good.

I have added a new option called "width" to the styles dictionary. With this it is possible to set the width of the InfoWindow by specifying either a numeric value (pixel), or a percentage (0.0-1.0) or 50%.

### CODE REVIEW

**Comment by Hirbod** [comment]
Looks good to me. We'll wait until someone or masashi had find time to develop it for android.

**Comment by trancee** [comment]
@Hirbod, I actually made the commit for both platforms. Could someone review and test my pull request, and if all is good, push it into the master branch? It already works for me as expected. Thanks!

**Comment by Hirbod** [comment]
Your right, sorry for that. Did not look close enough. I'm fine with that but the final decision has to be made by Masashi. He is very busy these days, please be patient.

**Comment by Hirbod** [comment]
@masashiGMS @wf9a5m75 I'd like to merge this. Ok?

**Comment by Hirbod** [comment]
Dear @trancee would you please be so kind and provide a short documentation? I would like to add it to the wiki and finally merge this one here

**Comment by trancee** [comment]
@Hirbod, thanks for finally merging this pull request. It has been quite some time.

Generally, I have tried to apply the same logic as in the original Google Maps implementation, with one slight difference. Besides the option <b>maxWidth</b> for defining the maximum width of the InfoWindow, there is a new option <b>width</b> to define the initial width of the InfoWindow. This can be percentage (%) or just a numeric value from 0.0 to 1.0 for percentile representation, or the numeric width in pixels.

I hope that helps.

**Comment by Hirbod** [comment]
@trancee thanks, could you please provide some examples what is possible for the documentation. I have limited time currently.

**Comment by trancee** [comment]
@Hirbod yes, sure. That is an example how I am using it in my project:

<pre>map.addMarker (
	{
		"position": position,

		"title": "This is the title.",
		"snippet": "And the description of this marker.",

		"styles": {
			"maxWidth": "80%"
		},

		// allows all users to drag the marker.
		"draggable": false
	}, ...</pre>

**Comment by Hirbod** [comment]
@trancee just merged your code, but I get:

```log
...platforms/ios/Nachbarschaft/Plugins/plugin.google.maps/GoogleMapsViewController.m:385:27: error: 
      no visible @interface for 'NSString' declares the selector 'isNumeric:'
                } else if ([widthString isNumeric:widthString]) {
                            ~~~~~~~~~~~ ^~~~~~~~~
...platforms/ios/Nachbarschaft/Plugins/plugin.google.maps/GoogleMapsViewController.m:408:27: error: 
      no visible @interface for 'NSString' declares the selector 'isNumeric:'
                } else if ([widthString isNumeric:widthString]) {

**Comment by Hirbod** [comment]
I'll change your code.

```obj-c
        NSNumberFormatter *nf = [[NSNumberFormatter alloc] init]; // new
        BOOL isNumeric = [nf numberFromString:widthString] != nil; // new
...
...
...
		//} else if ([widthString isNumeric:widthString]) {
		} else if (isNumeric) {
```

**Comment by trancee** [comment]
Strange, I did not get those errors. But thanks for fixing them!

**Pull request merged**
