### PR TITLE
added settings for watchdogtimer / complete rewrite of remote marker downloads

### PR DESCRIPTION
**Pull request by Hirbod**
Please mention this function in WIKI

### CODE REVIEW

**Comment by Hirbod** [comment]
Hi Masashi, since you changed my code a bit, you can't merge it. Would you incoporate my watchdog method manually? This would be nice!

**Comment by wf9a5m75** [comment]
Your code is already in the test branch.

**Comment by Hirbod** [comment]
Watchdog not. I had to incoporate it myself after I've installed the test branch

**Comment by Hirbod** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/test/www/googlemaps-cdv-plugin.js#L2040

Nope... not in test branch

**Comment by Hirbod** [comment]
?

**Comment by Hirbod** [comment]
@wf9a5m75 you ignore me? :(

**Comment by wf9a5m75** [comment]
No, it's really busy.

**Comment by Hirbod** [comment]
Want to pull app into the store in 3-4 days.. thanks why I'm pushing so much.. sorry

**Comment by wf9a5m75** [comment]
Thank you for your help @Hirbod

**Comment by Hirbod** [comment]
damn... now you did overrite your marker edits.. there was old code in my PR

**Comment by Hirbod** [comment]
Revert please and please, only manual PR the JS Files for WatchDog

**Comment by Hirbod** [comment]
#337

**Comment by Hirbod** [comment]
@wf9a5m75 
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/commit/da4ca9448dee7a253e387e818d85fa37df6e2213

**Comment by Hirbod** [comment]
and i really don't understand your organizing.  masashi_dev, master and test. All the PRs and fixes are mixed or missing or invalid now?!

**Comment by wf9a5m75** [comment]
Removed your code from Marker.m at once.

**Comment by Hirbod** [comment]
I don't really understand. And where is your improved version of my code?

**Comment by wf9a5m75** [comment]
masashi_dev's code for me , which includes cordova files.
master is master.
test is the beta test version.

Because of many people ask me many things, such as test, new feature, bug fix ... (you may know), I need to do coding in parallel.
That's why branch are increasing.

**Comment by Hirbod** [comment]
Allright. Cause usally "test" was your branch for "nearly" final. And now I can't use it anymore. Need to wait till you incorporate all the fixes and new things. Hope you realease 1.2.5 today which has all the new improvements

**Comment by wf9a5m75** [comment]
So is this your final code, isn't it?
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/337#issuecomment-71350970

**Comment by Hirbod** [comment]
Yeah, everything allright. But you improved the code because of marker. But I see you've merged the correct code to masashi_dev

**Comment by Hirbod** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/masashi_dev/src/ios/GoogleMaps/Marker.m#L480-L528

This one is correct

**Pull request merged**
